// 25-26 season setup data: prior-season (24-25) final standings, post-drop keeper rosters,
// actual draft picks, and mid-season (All-Star break) draft results.
// Split out of roster_tracker.html to keep the main file size down; loaded via <script src> before the app script.

// 2024-25 final standings — determines 25-26 draft order (rank 9 picks first)
const FINAL_STANDINGS_2425 = {
  'Motor City Wings':    {rank:1, pts:1152},
  'Pernicious Puckers':  {rank:2, pts:1107},
  'Damage Inc.':         {rank:3, pts:1083},
  'Bossy Posse':         {rank:4, pts:1053},
  'Dumb and Goalie To':  {rank:5, pts:1034},
  'Killer Whales':       {rank:6, pts:1022},
  'Silence of the Lamb': {rank:7, pts:1010},
  'Muller Time!':        {rank:8, pts:1007},
  'Blue Line Bangers':   {rank:9, pts:998},
};

// Manual cap overrides for 25-26 — used when PuckPedia sync doesn't have the contract.
const MANUAL_CAPS_2526 = {
  'max shabanov_F': { cap: 0.9750, yrStr: 'Yr 1 / 1' },
};

// Actual pre-draft 25-26 rosters (after drops, before draft picks).
// Keys = normName(name).toLowerCase() — absent players had no roster spot going into the draft.
// Ivan Demidov absent: dropped due to mid-season pickup rule; re-drafted with BLB's 1st pick.
const ACTUAL_ROSTER_2526 = {
  // Blue Line Bangers
  'mackenzie weegar':'Blue Line Bangers','brandon montour':'Blue Line Bangers',
  'gustav forsling':'Blue Line Bangers','jack eichel':'Blue Line Bangers',
  'nico hischier':'Blue Line Bangers','adrian kempe':'Blue Line Bangers',
  'alex tuch':'Blue Line Bangers','jared mccann':'Blue Line Bangers',
  'macklin celebrini':'Blue Line Bangers','adam fantilli':'Blue Line Bangers',
  'jordan spence':'Blue Line Bangers','michael kesselring':'Blue Line Bangers',
  'connor hellebuyck':'Blue Line Bangers',
  // Bossy Posse
  'evan bouchard':'Bossy Posse','adam fox':'Bossy Posse',
  'nathan mackinnon':'Bossy Posse','robert thomas':'Bossy Posse',
  'tage thompson':'Bossy Posse','kyle connor':'Bossy Posse',
  'ryan nugenthopkins':'Bossy Posse','juraj slafkovsky':'Bossy Posse',
  'shane wright':'Bossy Posse','jackson lacombe':'Bossy Posse',
  'matt coronato':'Bossy Posse',
  // Damage Inc.
  'nikita kucherov':'Damage Inc.','mikko rantanen':'Damage Inc.',
  'brayden point':'Damage Inc.','luke hughes':'Damage Inc.',
  'matt boldy':'Damage Inc.','dylan strome':'Damage Inc.',
  'drake batherson':'Damage Inc.','dylan guenther':'Damage Inc.',
  'adam boqvist':'Damage Inc.','kirill marchenko':'Damage Inc.',
  'leo carlsson':'Damage Inc.','simon nemec':'Damage Inc.',
  'philip broberg':'Damage Inc.','sam montembeault':'Damage Inc.',
  // Dumb and Goalie To
  'cale makar':'Dumb and Goalie To','david pastrnak':'Dumb and Goalie To',
  'thomas harley':'Dumb and Goalie To','brandon hagel':'Dumb and Goalie To',
  'cole caufield':'Dumb and Goalie To','sean monahan':'Dumb and Goalie To',
  'jonathan drouin':'Dumb and Goalie To','jack quinn':'Dumb and Goalie To',
  'mackenzie blackwood':'Dumb and Goalie To','stuart skinner':'Dumb and Goalie To',
  'morgan geekie':'Dumb and Goalie To','dmitri voronkov':'Dumb and Goalie To',
  'seamus casey':'Dumb and Goalie To','jiri kulich':'Dumb and Goalie To',
  // Killer Whales
  'victor hedman':'Killer Whales','auston matthews':'Killer Whales',
  'jack hughes':'Killer Whales','josh morrissey':'Killer Whales',
  'dustin wolf':'Killer Whales','connor bedard':'Killer Whales',
  'anze kopitar':'Killer Whales','seth jarvis':'Killer Whales',
  'quinton byfield':'Killer Whales','jamie drysdale':'Killer Whales',
  'will smith':'Killer Whales','william eklund':'Killer Whales',
  'cole perfetti':'Killer Whales','jacob markstrom':'Killer Whales',
  'dylan holloway':'Killer Whales',
  // Motor City Wings
  'kirill kaprizov':'Motor City Wings','sidney crosby':'Motor City Wings',
  'zach werenski':'Motor City Wings','jake guentzel':'Motor City Wings',
  'shayne gostisbehere':'Motor City Wings','clayton keller':'Motor City Wings',
  'dylan larkin':'Motor City Wings','lucas raymond':'Motor City Wings',
  'brandt clarke':'Motor City Wings','olen zellweger':'Motor City Wings',
  'marco rossi':'Motor City Wings','pavel dorofeyev':'Motor City Wings',
  'jake oettinger':'Motor City Wings','connor mcmichael':'Motor City Wings',
  'marco kasper':'Motor City Wings',
  // Muller Time!
  'mitch marner':'Muller Time!','roope hintz':'Muller Time!',
  'shea theodore':'Muller Time!','martin necas':'Muller Time!',
  'vincent trocheck':'Muller Time!','bryan rust':'Muller Time!',
  'carter verhaeghe':'Muller Time!','aliaksei protas':'Muller Time!',
  'logan cooley':'Muller Time!','matvei michkov':'Muller Time!',
  'zayne parekh':'Muller Time!','carter yakemchuk':'Muller Time!',
  'denton mateychuk':'Muller Time!',
  // Pernicious Puckers
  'quinn hughes':'Pernicious Puckers','leon draisaitl':'Pernicious Puckers',
  'jt miller':'Pernicious Puckers','jason robertson':'Pernicious Puckers',
  'sam reinhart':'Pernicious Puckers','tim stutzle':'Pernicious Puckers',
  'lane hutson':'Pernicious Puckers','nick suzuki':'Pernicious Puckers',
  'logan stankoven':'Pernicious Puckers','kent johnson':'Pernicious Puckers',
  'filip gustavsson':'Pernicious Puckers','simon edvinsson':'Pernicious Puckers',
  'thatcher demko':'Pernicious Puckers','artyom levshunov':'Pernicious Puckers',
  'tony deangelo':'Pernicious Puckers',
  // Silence of the Lamb
  'logan thompson':'Silence of the Lamb','connor mcdavid':'Silence of the Lamb',
  'jesper bratt':'Silence of the Lamb','rasmus andersson':'Silence of the Lamb',
  'mark scheifele':'Silence of the Lamb','brad marchand':'Silence of the Lamb',
  'patrick kane':'Silence of the Lamb','matt duchene':'Silence of the Lamb',
  'conor garland':'Silence of the Lamb','matthew knies':'Silence of the Lamb',
  'cutter gauthier':'Silence of the Lamb','darren raddysh':'Silence of the Lamb',
  'jason zucker':'Silence of the Lamb','erik gustafsson':'Silence of the Lamb',
};

// Actual 25-26 draft picks (players added via draft, not in pre-draft rosters above).
// Keys = normName(name).toLowerCase(), values = fantasy team name.
const ACTUAL_DRAFT_2526 = {
  // Blue Line Bangers (7 picks — Ivan Demidov re-drafted after mandatory ELC drop)
  'ivan demidov':'Blue Line Bangers',
  'jordan binnington':'Blue Line Bangers',
  'mason lohrei':'Blue Line Bangers',
  'matthew savoie':'Blue Line Bangers',
  'rickard rakell':'Blue Line Bangers',
  'sebastian aho':'Blue Line Bangers',
  'tyson foerster':'Blue Line Bangers',
  // Bossy Posse (9 picks)
  'adin hill':'Bossy Posse',
  'jet greaves':'Bossy Posse',
  'joel eriksson ek':'Bossy Posse',
  'matthew schaefer':'Bossy Posse',
  'mavrik bourque':'Bossy Posse',
  'sam dickinson':'Bossy Posse',
  'scott morrow':'Bossy Posse',
  'ville koivunen':'Bossy Posse',
  'zach benson':'Bossy Posse',
  // Damage Inc. (6 picks)
  'anthony stolarz':'Damage Inc.',
  'isaac howard':'Damage Inc.',
  'kevin korchinski':'Damage Inc.',
  'logan mailloux':'Damage Inc.',
  'max shabanov':'Damage Inc.',
  'william nylander':'Damage Inc.',
  // Dumb and Goalie To (6 picks)
  'claude giroux':'Dumb and Goalie To',
  'gabriel landeskog':'Dumb and Goalie To',
  'nick blankenburg':'Dumb and Goalie To',
  'rasmus dahlin':'Dumb and Goalie To',
  'sam rinzel':'Dumb and Goalie To',
  'zack bolduc':'Dumb and Goalie To',
  // Killer Whales (5 picks)
  'frank nazar':'Killer Whales',
  'john klingberg':'Killer Whales',
  'matias maccelli':'Killer Whales',
  'morgan rielly':'Killer Whales',
  'sean durzi':'Killer Whales',
  // Motor City Wings (5 picks)
  'braden schneider':'Motor City Wings',
  'brent burns':'Motor City Wings',
  'jimmy snuggerud':'Motor City Wings',
  'john gibson':'Motor City Wings',
  'mackie samoskevich':'Motor City Wings',
  // Muller Time! (7 picks) — in actual draft order
  'zeev buium':'Muller Time!',
  'wyatt johnston':'Muller Time!',
  'roman josi':'Muller Time!',
  'darcy kuemper':'Muller Time!',
  'ryan leonard':'Muller Time!',
  'ryan donato':'Muller Time!',
  'karel vejmelka':'Muller Time!',
  // Pernicious Puckers (5 picks)
  'danila yurov':'Pernicious Puckers',
  'dylan cozens':'Pernicious Puckers',
  'jake walman':'Pernicious Puckers',
  'john tavares':'Pernicious Puckers',
  'liam ohgren':'Pernicious Puckers',
  // Silence of the Lamb (6 picks)
  'alexander nikishin':'Silence of the Lamb',
  'andrei vasilevskiy':'Silence of the Lamb',
  'jonathan toews':'Silence of the Lamb',
  'michael misa':'Silence of the Lamb',
  'noah hanifin':'Silence of the Lamb',
  'pavel mintyukov':'Silence of the Lamb',
};

// CBS Sports 25-26 preseason projections (captured 2026-06-12), keyed by normName_PG.
// HGHL pts = G+A (skaters) or W*2+SO*3 (goalies). Display-only on the 25-26 Players view
// (not included in ppts2526blend) -- useful as a 4th opinion for fringe players.
const PROJ2526_CBS = {
  'aaron ekblad_D': 39,
  'aatu raty_F': 25,
  'adam boqvist_D': 29,
  'adam edstrom_F': 15,
  'adam erne_F': 6,
  'adam fantilli_F': 54,
  'adam fox_D': 70,
  'adam gaudette_F': 24,
  'adam ginning_D': 17,
  'adam henrique_F': 39,
  'adam klapka_F': 24,
  'adam larsson_D': 25,
  'adam lowry_F': 34,
  'adam pelech_D': 27,
  'adam wilsby_D': 17,
  'adin hill_G': 78,
  'adrian kempe_F': 83,
  'aj greer_F': 18,
  'akil thomas_F': 6,
  'akira schmid_G': 27,
  'albert johansson_D': 13,
  'alec martinez_D': 7,
  'alec regula_D': 26,
  'alex alexeyev_D': 2,
  'alex barreboulet_F': 7,
  'alex carrier_D': 26,
  'alex debrincat_F': 66,
  'alex holtz_F': 25,
  'alex iafallo_F': 29,
  'alex kerfoot_F': 18,
  'alex killorn_F': 47,
  'alex laferriere_F': 36,
  'alex lyon_G': 23,
  'alex nedeljkovic_G': 19,
  'alex newhook_F': 38,
  'alex nikishin_D': 29,
  'alex nylander_F': 16,
  'alex ovechkin_F': 84,
  'alex petrovic_D': 7,
  'alex romanov_D': 24,
  'alex texier_F': 35,
  'alex tuch_F': 68,
  'alex turcotte_F': 28,
  'alex vlasic_D': 26,
  'alex wennberg_F': 30,
  'alexandar georgiev_G': 1,
  'alexander alexeyev_D': 2,
  'alexander holtz_F': 25,
  'alexander kerfoot_F': 18,
  'alexander nikishin_D': 29,
  'alexander petrovic_D': 7,
  'alexander romanov_D': 24,
  'alexandre barreboulet_F': 7,
  'alexandre carrier_D': 26,
  'alexandre debrincat_F': 66,
  'alexandre iafallo_F': 29,
  'alexandre killorn_F': 47,
  'alexandre laferriere_F': 36,
  'alexandre lyon_G': 23,
  'alexandre nedeljkovic_G': 19,
  'alexandre newhook_F': 38,
  'alexandre nylander_F': 16,
  'alexandre ovechkin_F': 84,
  'alexandre texier_F': 35,
  'alexandre tuch_F': 68,
  'alexandre turcotte_F': 28,
  'alexandre vlasic_D': 26,
  'alexandre wennberg_F': 30,
  'alexei protas_F': 55,
  'alexei toropchenko_F': 22,
  'alexis lafreniere_F': 52,
  'anders lee_F': 48,
  'andre burakovsky_F': 33,
  'andreas athanasiou_F': 8,
  'andreas englund_D': 3,
  'andrei kuzmenko_F': 50,
  'andrei svechnikov_F': 68,
  'andrei vasilevskiy_G': 84,
  'andrew agozzino_F': 6,
  'andrew copp_F': 33,
  'andrew mangiapane_F': 36,
  'andrew peeke_D': 19,
  'angus crookshank_F': 5,
  'anthony beauvillier_F': 30,
  'anthony cirelli_F': 54,
  'anthony duclair_F': 39,
  'anthony mantha_F': 52,
  'anthony richard_F': 13,
  'anthony stolarz_G': 77,
  'anton forsberg_G': 27,
  'anton lundell_F': 49,
  'anze kopitar_F': 75,
  'arber xhekaj_D': 12,
  'arseny gritsyuk_F': 43,
  'arsh bains_F': 5,
  'artem zub_D': 26,
  'artemi panarin_F': 100,
  'arthur kaliyev_F': 8,
  'arttu hyry_F': 40,
  'artturi lehkonen_F': 60,
  'arturs silovs_G': 22,
  'artyom levshunov_D': 27,
  'arvid soderblom_G': 20,
  'austin watson_F': 4,
  'auston matthews_F': 99,
  'axel jonssonfjallby_F': 6,
  'axel sandin pellikka_D': 24,
  'barclay goodrow_F': 12,
  'barrett hayton_F': 40,
  'beck malenstyn_F': 17,
  'beckett sennecke_F': 40,
  'ben chiarot_D': 16,
  'ben hutton_D': 18,
  'ben meyers_F': 3,
  'benjamin kindel_F': 46,
  'benoitolivier groulx_F': 2,
  'berkly catton_F': 44,
  'blake coleman_F': 47,
  'blake lizotte_F': 24,
  'bo horvat_F': 65,
  'bobby brink_F': 41,
  'bobby mcmann_F': 34,
  'bokondji imama_F': 1,
  'boone jenner_F': 61,
  'boris katchouk_F': 11,
  'bowen byram_D': 34,
  'brad marchand_F': 73,
  'braden schneider_D': 19,
  'bradley marchand_F': 73,
  'brady martin_F': 38,
  'brady skjei_D': 37,
  'brady tkachuk_F': 71,
  'braeden cootes_F': 43,
  'brandon carlo_D': 15,
  'brandon duhaime_F': 18,
  'brandon hagel_F': 83,
  'brandon montour_D': 41,
  'brandon saad_F': 43,
  'brandon tanev_F': 22,
  'brandt clarke_D': 34,
  'brayden mcnabb_D': 26,
  'brayden pachal_D': 12,
  'brayden point_F': 90,
  'brayden schenn_F': 51,
  'brendan brisson_F': 7,
  'brendan gallagher_F': 38,
  'brendan gaunce_F': 5,
  'brendan smith_D': 6,
  'brenden dillon_D': 19,
  'brennan othmann_F': 2,
  'brent burns_D': 36,
  'brett berard_F': 26,
  'brett howden_F': 33,
  'brett kulak_D': 20,
  'brett leason_F': 9,
  'brett pesce_D': 18,
  'brian dumoulin_D': 23,
  'brock boeser_F': 62,
  'brock faber_D': 38,
  'brock mcginn_F': 7,
  'brock nelson_F': 74,
  'bryan rust_F': 71,
  'cale fleury_D': 11,
  'cale makar_D': 91,
  'caleb jones_D': 9,
  'calle jarnkrok_F': 28,
  'calum ritchie_F': 31,
  'calvin de haan_D': 4,
  'calvin pickard_G': 25,
  'cam butler_F': 40,
  'cam fowler_D': 54,
  'cam talbot_G': 23,
  'cam york_D': 28,
  'cameron butler_F': 40,
  'cameron fowler_D': 54,
  'cameron talbot_G': 23,
  'cameron york_D': 28,
  'carl grundstrom_F': 5,
  'carson meyer_F': 24,
  'carson soucy_D': 16,
  'carter verhaeghe_F': 73,
  'carter yakemchuk_D': 3,
  'casey cizikas_F': 22,
  'casey desmith_G': 28,
  'casey mittelstadt_F': 45,
  'chad ruhwedel_D': 3,
  'chandler stephenson_F': 53,
  'charlesalexis legault_D': 27,
  'charlie coyle_F': 50,
  'charlie lindgren_G': 26,
  'charlie mcavoy_D': 45,
  'chris kreider_F': 50,
  'chris tanev_D': 20,
  'chris wagner_F': 2,
  'christian dvorak_F': 31,
  'christian fischer_F': 6,
  'christopher kreider_F': 50,
  'christopher tanev_D': 20,
  'christopher wagner_F': 2,
  'claude giroux_F': 58,
  'clayton keller_F': 86,
  'cody ceci_D': 22,
  'cody glass_F': 26,
  'cole caufield_F': 72,
  'cole guttman_F': 13,
  'cole koepke_F': 24,
  'cole perfetti_F': 49,
  'cole reinhardt_F': 18,
  'cole schwindt_F': 15,
  'cole sillinger_F': 41,
  'cole smith_F': 17,
  'colin blackwell_F': 25,
  'colin miller_D': 21,
  'collin graf_F': 30,
  'colton dach_F': 22,
  'colton parayko_D': 40,
  'colton sissons_F': 35,
  'connor bedard_F': 74,
  'connor brown_F': 22,
  'connor clifton_D': 19,
  'connor dewar_F': 19,
  'connor hellebuyck_G': 79,
  'connor mcdavid_F': 124,
  'connor mcmichael_F': 51,
  'connor murphy_D': 21,
  'connor zary_F': 41,
  'conor garland_F': 44,
  'conor geekie_F': 24,
  'conor sheary_F': 17,
  'conor timmins_D': 21,
  'corey perry_F': 28,
  'craig smith_F': 7,
  'curtis lazar_F': 24,
  'cutter gauthier_F': 46,
  'daemon hunt_D': 12,
  'dakota joshua_F': 35,
  'dakota mermis_D': 5,
  'damon severson_D': 36,
  'dan sprong_F': 12,
  'dan vladar_G': 23,
  'daniel sprong_F': 12,
  'daniel vladar_G': 23,
  'daniil but_F': 44,
  'daniil miromanov_D': 20,
  'daniil tarasov_G': 26,
  'danila yurov_F': 42,
  'dante fabbro_D': 27,
  'danton heinen_F': 11,
  'darcy kuemper_G': 76,
  'darnell nurse_D': 30,
  'darren raddysh_D': 36,
  'dave gustafsson_F': 15,
  'dave jiricek_D': 21,
  'dave kampf_F': 6,
  'dave pastrnak_F': 101,
  'dave perron_F': 41,
  'dave rittich_G': 22,
  'dave savard_D': 8,
  'david gustafsson_F': 15,
  'david jiricek_D': 21,
  'david kampf_F': 6,
  'david pastrnak_F': 101,
  'david perron_F': 41,
  'david rittich_G': 22,
  'david savard_D': 8,
  'dawson mercer_F': 35,
  'declan chisholm_D': 21,
  'dennis cholowski_D': 24,
  'dennis gilbert_D': 5,
  'dennis hildeby_G': 26,
  'denton mateychuk_D': 24,
  'derek forbort_D': 13,
  'derek ryan_F': 4,
  'devin cooley_G': 21,
  'devin shore_F': 4,
  'devon toews_D': 47,
  'dmitri voronkov_F': 50,
  'dmitriy simashev_D': 24,
  'dmitry kulikov_D': 17,
  'dmitry orlov_D': 23,
  'dominic james_F': 53,
  'dominic toninato_F': 6,
  'donovan sebrango_D': 22,
  'dougie hamilton_D': 53,
  'drake batherson_F': 67,
  'drew doughty_D': 51,
  'drew helleson_D': 19,
  'drew oconnor_F': 28,
  'dryden hunt_F': 8,
  'dustin wolf_G': 62,
  'dylan cozens_F': 48,
  'dylan demelo_D': 26,
  'dylan guenther_F': 67,
  'dylan holloway_F': 47,
  'dylan larkin_F': 73,
  'dylan mcilrath_D': 12,
  'dylan samberg_D': 17,
  'dylan strome_F': 84,
  'easton cowan_F': 47,
  'eeli tolvanen_F': 43,
  'eetu luostarinen_F': 33,
  'egor afanasyev_F': 5,
  'egor zamula_D': 23,
  'elias lindholm_F': 49,
  'elias pettersson_D': 9,
  'elias pettersson_F': 67,
  'elmer soderblom_F': 37,
  'elvis merzlikins_G': 73,
  'emil andrae_D': 4,
  'emil bemstrom_F': 7,
  'emil heineman_F': 21,
  'emil martinsen lilleberg_D': 17,
  'emmitt finnie_F': 43,
  'eric comrie_G': 26,
  'eric robinson_F': 28,
  'erik brannstrom_D': 7,
  'erik cernak_D': 20,
  'erik gudbranson_D': 30,
  'erik gustafsson_D': 9,
  'erik haula_F': 28,
  'erik johnson_D': 4,
  'erik karlsson_D': 56,
  'esa lindell_D': 24,
  'ethan bear_D': 6,
  'ethan cardwell_F': 29,
  'ethan del mastro_D': 17,
  'ethen frank_F': 8,
  'evan bouchard_D': 76,
  'evan rodrigues_F': 42,
  'evander kane_F': 36,
  'evgeni malkin_F': 65,
  'evgenii dadonov_F': 33,
  'fabian zetterlund_F': 50,
  'fedor svechkov_F': 27,
  'filip chytil_F': 37,
  'filip forsberg_F': 80,
  'filip gustavsson_G': 70,
  'filip hallander_F': 44,
  'filip hronek_D': 40,
  'frank nazar_F': 38,
  'frank vatrano_F': 58,
  'fraser minten_F': 15,
  'frederick gaudreau_F': 30,
  'frederik andersen_G': 86,
  'gabe landeskog_F': 56,
  'gabe vilardi_F': 67,
  'gabriel landeskog_F': 56,
  'gabriel vilardi_F': 67,
  'gage goncalves_F': 30,
  'garnet hathaway_F': 22,
  'gavin brindley_F': 47,
  'givani smith_F': 3,
  'guillaume brisebois_D': 18,
  'gustav forsling_D': 37,
  'gustav nyquist_F': 61,
  'hampus lindholm_D': 27,
  'harrison brunicke_D': 25,
  'haydn fleury_D': 16,
  'hendrix lapierre_F': 38,
  'henri jokiharju_D': 18,
  'henry thrun_D': 8,
  'hudson fasching_F': 7,
  'ian cole_D': 13,
  'ian mitchell_D': 3,
  'ian moore_D': 26,
  'igor shesterkin_G': 72,
  'ilya lyubushkin_D': 14,
  'ilya mikheyev_F': 28,
  'ilya solovyov_D': 32,
  'ilya sorokin_G': 65,
  'isaac howard_F': 48,
  'isaak phillips_D': 8,
  'isac lundestrom_F': 21,
  'isaiah george_D': 13,
  'ivan barbashev_F': 51,
  'ivan demidov_F': 47,
  'ivan ivan_F': 6,
  'ivan miroshnichenko_F': 25,
  'ivan provorov_D': 36,
  'jaccob slavin_D': 33,
  'jack drury_F': 26,
  'jack eichel_F': 98,
  'jack finley_F': 49,
  'jack hughes_F': 94,
  'jack johnson_D': 4,
  'jack mcbain_F': 29,
  'jack quinn_F': 46,
  'jack roslovic_F': 15,
  'jack st ivany_D': 1,
  'jack studnicka_F': 2,
  'jack thompson_D': 27,
  'jack williams_F': 45,
  'jackson blake_F': 38,
  'jackson lacombe_D': 36,
  'jacob allen_G': 22,
  'jacob bean_D': 12,
  'jacob bernarddocker_D': 16,
  'jacob bryson_D': 15,
  'jacob christiansen_D': 11,
  'jacob debrusk_F': 46,
  'jacob evans_F': 34,
  'jacob guentzel_F': 94,
  'jacob lucchini_F': 3,
  'jacob markstrom_G': 70,
  'jacob mccabe_D': 29,
  'jacob middleton_D': 26,
  'jacob moverare_D': 10,
  'jacob neighbours_F': 48,
  'jacob oettinger_G': 79,
  'jacob sanderson_D': 50,
  'jacob trouba_D': 19,
  'jacob walman_D': 41,
  'jaden schwartz_F': 49,
  'jake allen_G': 22,
  'jake bean_D': 12,
  'jake bernarddocker_D': 16,
  'jake bryson_D': 15,
  'jake christiansen_D': 11,
  'jake debrusk_F': 46,
  'jake evans_F': 34,
  'jake guentzel_F': 94,
  'jake lucchini_F': 3,
  'jake markstrom_G': 70,
  'jake mccabe_D': 29,
  'jake middleton_D': 26,
  'jake moverare_D': 10,
  'jake neighbours_F': 48,
  'jake oettinger_G': 79,
  'jake sanderson_D': 50,
  'jake trouba_D': 19,
  'jake walman_D': 41,
  'jakob chychrun_D': 49,
  'jakob pelletier_F': 12,
  'jakub dobes_G': 26,
  'jakub lauko_F': 5,
  'jakub vrana_F': 8,
  'jalen chatfield_D': 22,
  'james hamblin_F': 2,
  'james van riemsdyk_F': 40,
  'jamie benn_F': 42,
  'jamie drysdale_D': 25,
  'jamie oleksiak_D': 17,
  'jan rutta_D': 7,
  'jani hakanpaa_D': 4,
  'jani nyman_F': 40,
  'janis moser_D': 25,
  'jansen harkins_F': 6,
  'jared mccann_F': 69,
  'jared spurgeon_D': 40,
  'jaret andersondolan_F': 5,
  'jason dickinson_F': 35,
  'jason robertson_F': 77,
  'jason zucker_F': 50,
  'jaycob megna_D': 2,
  'jayden struble_D': 18,
  'jeangabriel pageau_F': 39,
  'jeff malott_F': 8,
  'jeff petry_D': 24,
  'jeff skinner_F': 36,
  'jeremy lauzon_D': 13,
  'jeremy swayman_G': 60,
  'jesper boqvist_F': 27,
  'jesper bratt_F': 86,
  'jesper fast_F': 7,
  'jesper wallstedt_G': 21,
  'jesperi kotkaniemi_F': 31,
  'jesse puljujarvi_F': 9,
  'jesse ylonen_F': 5,
  'jet greaves_G': 24,
  'jett luchanko_F': 34,
  'jimmy snuggerud_F': 42,
  'jimmy vesey_F': 8,
  'jiri kulich_F': 31,
  'joakim kemell_F': 34,
  'joel armia_F': 34,
  'joel edmundson_D': 18,
  'joel eriksson ek_F': 58,
  'joel farabee_F': 39,
  'joel hanley_D': 12,
  'joel hofer_G': 25,
  'joel kiviranta_F': 18,
  'joey anderson_F': 9,
  'joey daccord_G': 69,
  'john beecher_F': 13,
  'john carlson_D': 56,
  'john gibson_G': 68,
  'john hayden_F': 3,
  'john klingberg_D': 18,
  'john ludvig_D': 6,
  'john marino_D': 28,
  'john tavares_F': 71,
  'johnathan kovacevic_D': 9,
  'johnjason peterka_F': 61,
  'jon merrill_D': 4,
  'jonah gadjovich_F': 10,
  'jonas brodin_D': 31,
  'jonas johansson_G': 27,
  'jonas rondbjerg_F': 3,
  'jonas siegenthaler_D': 13,
  'jonatan berggren_F': 29,
  'jonathan drouin_F': 49,
  'jonathan huberdeau_F': 57,
  'jonathan lekkerimaki_F': 22,
  'jonathan marchessault_F': 59,
  'jonathan quick_G': 25,
  'jonathan toews_F': 50,
  'jonny brodzinski_F': 27,
  'joonas korpisalo_G': 22,
  'jordan binnington_G': 74,
  'jordan eberle_F': 53,
  'jordan greenway_F': 31,
  'jordan harris_D': 16,
  'jordan kyrou_F': 72,
  'jordan martinook_F': 36,
  'jordan oesterle_D': 5,
  'jordan spence_D': 26,
  'jordan staal_F': 34,
  'joseph veleno_F': 24,
  'josh anderson_F': 26,
  'josh brown_D': 5,
  'josh doan_F': 36,
  'josh mahura_D': 16,
  'josh manson_D': 28,
  'josh morrissey_D': 67,
  'josh norris_F': 53,
  'josh roy_F': 9,
  'joshua anderson_F': 26,
  'joshua brown_D': 5,
  'joshua doan_F': 36,
  'joshua mahura_D': 16,
  'joshua manson_D': 28,
  'joshua morrissey_D': 67,
  'joshua norris_F': 53,
  'joshua roy_F': 9,
  'jt compher_F': 42,
  'jt miller_F': 90,
  'juha jaaska_F': 22,
  'juho lammikko_F': 37,
  'julien gauthier_F': 8,
  'juraj slafkovsky_F': 55,
  'justin barron_D': 18,
  'justin brazeau_F': 29,
  'justin danforth_F': 30,
  'justin dowling_F': 4,
  'justin faulk_D': 39,
  'justin holl_D': 3,
  'justin hryckowian_F': 40,
  'justin kirkland_F': 35,
  'justin sourdif_F': 42,
  'justus annunen_G': 21,
  'juuse saros_G': 58,
  'juuso parssinen_F': 28,
  'juuso valimaki_D': 5,
  'kaapo kakko_F': 28,
  'kaedan korczak_D': 22,
  'kaiden guhle_D': 28,
  'kailer yamamoto_F': 26,
  'kandre miller_D': 31,
  'karel vejmelka_G': 69,
  'kasperi kapanen_F': 24,
  'keaton middleton_D': 1,
  'keegan kolesar_F': 24,
  'kent johnson_F': 58,
  'kevin bahl_D': 16,
  'kevin fiala_F': 70,
  'kevin hayes_F': 30,
  'kevin korchinski_D': 6,
  'kevin labanc_F': 10,
  'kevin lankinen_G': 24,
  'kevin rooney_F': 4,
  'kevin stenlund_F': 19,
  'kiefer sherwood_F': 36,
  'kirby dach_F': 34,
  'kirill kaprizov_F': 103,
  'kirill marchenko_F': 66,
  'klim kostin_F': 6,
  'kris letang_D': 44,
  'kurtis macdermid_D': 3,
  'kyle burroughs_D': 11,
  'kyle connor_F': 95,
  'kyle mclean_F': 15,
  'kyle palmieri_F': 53,
  'landon slaggert_F': 17,
  'lane hutson_D': 68,
  'lars eller_F': 25,
  'lawson crouse_F': 31,
  'leevi merilainen_G': 24,
  'leo carlsson_F': 48,
  'leon draisaitl_F': 109,
  'liam obrien_F': 12,
  'liam ohgren_F': 20,
  'lian bichsel_D': 15,
  'linus karlsson_F': 16,
  'linus ullmark_G': 69,
  'logan cooley_F': 57,
  'logan mailloux_D': 37,
  'logan oconnor_F': 25,
  'logan stankoven_F': 44,
  'logan stanley_D': 14,
  'logan thompson_G': 74,
  'louis crevier_D': 12,
  'lucas raymond_F': 73,
  'lukas dostal_G': 62,
  'lukas reichel_F': 26,
  'luke evangelista_F': 36,
  'luke glendening_F': 9,
  'luke hughes_D': 49,
  'luke kunin_F': 28,
  'luke schenn_D': 9,
  'mackenzie blackwood_G': 80,
  'mackenzie weegar_D': 49,
  'mackie samoskevich_F': 38,
  'macklin celebrini_F': 75,
  'marat khusnutdinov_F': 15,
  'marc del gaizo_D': 5,
  'marc gatcomb_F': 20,
  'marc mclaughlin_F': 27,
  'marcedouard vlasic_D': 6,
  'marco kasper_F': 41,
  'marco rossi_F': 51,
  'marcus foligno_F': 34,
  'marcus johansson_F': 36,
  'marcus pettersson_D': 30,
  'mario ferraro_D': 22,
  'mark friedman_D': 1,
  'mark jankowski_F': 32,
  'mark kastelic_F': 16,
  'mark scheifele_F': 87,
  'mark stone_F': 79,
  'marshall rifai_D': 20,
  'martin fehervary_D': 27,
  'martin necas_F': 72,
  'martin pospisil_F': 27,
  'mason appleton_F': 29,
  'mason geertsen_D': 45,
  'mason lohrei_D': 32,
  'mason marchment_F': 47,
  'mason mctavish_F': 61,
  'mathew barzal_F': 76,
  'mathieu joseph_F': 32,
  'mathieu olivier_F': 29,
  'matias maccelli_F': 50,
  'mats zuccarello_F': 53,
  'matt benning_D': 4,
  'matt boldy_F': 78,
  'matt coronato_F': 44,
  'matt duchene_F': 65,
  'matt dumba_D': 12,
  'matt grzelcyk_D': 25,
  'matt highmore_F': 4,
  'matt kessel_D': 13,
  'matt knies_F': 48,
  'matt martin_F': 3,
  'matt nieto_F': 4,
  'matt poitras_F': 10,
  'matt rempe_F': 12,
  'matt robertson_D': 23,
  'matt roy_D': 28,
  'matt savoie_F': 42,
  'matt schaefer_D': 23,
  'matt tkachuk_F': 55,
  'matt wood_F': 29,
  'matthew benning_D': 4,
  'matthew boldy_F': 78,
  'matthew coronato_F': 44,
  'matthew duchene_F': 65,
  'matthew dumba_D': 12,
  'matthew grzelcyk_D': 25,
  'matthew highmore_F': 4,
  'matthew kessel_D': 13,
  'matthew knies_F': 48,
  'matthew martin_F': 3,
  'matthew nieto_F': 4,
  'matthew poitras_F': 10,
  'matthew rempe_F': 12,
  'matthew robertson_D': 23,
  'matthew roy_D': 28,
  'matthew savoie_F': 42,
  'matthew schaefer_D': 23,
  'matthew tkachuk_F': 55,
  'matthew wood_F': 29,
  'mattias ekholm_D': 42,
  'mattias janmark_F': 17,
  'mattias samuelsson_D': 17,
  'matty beniers_F': 45,
  'matvei michkov_F': 65,
  'mavrik bourque_F': 27,
  'max domi_F': 43,
  'max jones_F': 22,
  'max pacioretty_F': 14,
  'max sasson_F': 7,
  'maxim shabanov_F': 41,
  'maxim tsyplakov_F': 42,
  'maxwell crozier_D': 7,
  'michael amadio_F': 30,
  'michael brandseggnygard_F': 42,
  'michael bunting_F': 42,
  'michael carcone_F': 31,
  'michael kesselring_D': 28,
  'michael matheson_D': 49,
  'michael mccarron_F': 18,
  'michael misa_F': 39,
  'michael pezzetta_F': 4,
  'michael rasmussen_F': 27,
  'michael reilly_D': 32,
  'michael sgarbossa_F': 8,
  'mika zibanejad_F': 67,
  'mikael backlund_F': 36,
  'mikael granlund_F': 68,
  'mikael pyyhtia_F': 4,
  'mike amadio_F': 30,
  'mike brandseggnygard_F': 42,
  'mike bunting_F': 42,
  'mike carcone_F': 31,
  'mike kesselring_D': 28,
  'mike matheson_D': 49,
  'mike mccarron_F': 18,
  'mike misa_F': 39,
  'mike pezzetta_F': 4,
  'mike rasmussen_F': 27,
  'mike reilly_D': 32,
  'mike sgarbossa_F': 8,
  'mikey anderson_D': 24,
  'mikey eyssimont_F': 17,
  'mikhail sergachev_D': 51,
  'mikko rantanen_F': 98,
  'milan lucic_F': 45,
  'miles wood_F': 23,
  'miro heiskanen_D': 56,
  'mitch chaffee_F': 21,
  'mitch marner_F': 102,
  'mitch stephens_F': 3,
  'mitchell chaffee_F': 21,
  'mitchell marner_F': 102,
  'mitchell stephens_F': 3,
  'morgan barron_F': 18,
  'morgan frost_F': 43,
  'morgan geekie_F': 49,
  'morgan rielly_D': 53,
  'moritz seider_D': 42,
  'nate danielson_F': 42,
  'nate schmidt_D': 22,
  'nathan bastian_F': 18,
  'nathan mackinnon_F': 125,
  'nathan walker_F': 22,
  'nazem kadri_F': 70,
  'neal pionk_D': 40,
  'nic dowd_F': 29,
  'nicholas bjugstad_F': 40,
  'nicholas blankenburg_D': 18,
  'nicholas cousins_F': 19,
  'nicholas desimone_D': 17,
  'nicholas foligno_F': 43,
  'nicholas jensen_D': 20,
  'nicholas leddy_D': 19,
  'nicholas paul_F': 40,
  'nicholas robertson_F': 30,
  'nicholas schmaltz_F': 63,
  'nicholas seeler_D': 19,
  'nicholas suzuki_F': 87,
  'nick bjugstad_F': 40,
  'nick blankenburg_D': 18,
  'nick cousins_F': 19,
  'nick desimone_D': 17,
  'nick foligno_F': 43,
  'nick jensen_D': 20,
  'nick leddy_D': 19,
  'nick paul_F': 40,
  'nick robertson_F': 30,
  'nick schmaltz_F': 63,
  'nick seeler_D': 19,
  'nick suzuki_F': 87,
  'nicklaus perbix_D': 18,
  'nico hischier_F': 76,
  'nico sturm_F': 20,
  'nicolas aubekubel_F': 6,
  'nicolas deslauriers_F': 7,
  'nicolas hague_D': 10,
  'nicolas roy_F': 40,
  'nikita alexandrov_F': 2,
  'nikita chibrikov_F': 49,
  'nikita grebenkin_F': 27,
  'nikita kucherov_F': 137,
  'nikita nesterenko_F': 27,
  'nikita zadorov_D': 24,
  'niko mikkola_D': 20,
  'nikolai kovalenko_F': 8,
  'nikolaj ehlers_F': 71,
  'nikolas matinpalo_D': 6,
  'nils aman_F': 5,
  'nils hoglander_F': 21,
  'nils lundkvist_D': 18,
  'nino niederreiter_F': 39,
  'noah cates_F': 34,
  'noah dobson_D': 64,
  'noah gregor_F': 15,
  'noah hanifin_D': 47,
  'noah juulsen_D': 6,
  'noah laba_F': 47,
  'noah ostlund_F': 27,
  'noah philp_F': 21,
  'noel acciari_F': 12,
  'nolan allan_D': 6,
  'olen zellweger_D': 30,
  'oliver bjorkstrand_F': 68,
  'oliver bonk_D': 22,
  'oliver ekmanlarsson_D': 32,
  'oliver kapanen_F': 12,
  'oliver kylington_D': 8,
  'oliver wahlstrom_F': 4,
  'olle lycksell_F': 8,
  'olli maatta_D': 19,
  'ondrej palat_F': 33,
  'oskar back_F': 17,
  'oskar sundqvist_F': 25,
  'owen pickering_D': 3,
  'owen power_D': 40,
  'owen tippett_F': 52,
  'ozzy wiesblatt_F': 31,
  'parker ford_F': 45,
  'parker kelly_F': 20,
  'parker wotherspoon_D': 16,
  'pat brown_F': 2,
  'pat kane_F': 71,
  'pat maroon_F': 7,
  'patrick brown_F': 2,
  'patrick kane_F': 71,
  'patrick maroon_F': 7,
  'patrik laine_F': 50,
  'paul cotter_F': 25,
  'pavel buchnevich_F': 70,
  'pavel dorofeyev_F': 48,
  'pavel mintyukov_D': 32,
  'pavel zacha_F': 51,
  'petr mrazek_G': 21,
  'peyton krebs_F': 24,
  'phil broberg_D': 30,
  'phil tomasino_F': 37,
  'philip broberg_D': 30,
  'philip tomasino_F': 37,
  'philipp grubauer_G': 23,
  'philipp kurashev_F': 49,
  'philippe myers_D': 11,
  'phillip danault_F': 50,
  'phillip di giuseppe_F': 7,
  'pierre engvall_F': 26,
  'pierreluc dubois_F': 53,
  'pierreolivier joseph_D': 11,
  'pius suter_F': 42,
  'pontus holmberg_F': 24,
  'pyotr kochetkov_G': 29,
  'quinn hughes_D': 80,
  'quinton byfield_F': 59,
  'radek faksa_F': 21,
  'radko gudas_D': 20,
  'rafael harveypinard_F': 7,
  'rasmus andersson_D': 35,
  'rasmus dahlin_D': 69,
  'rasmus kupari_F': 3,
  'rasmus ristolainen_D': 17,
  'rasmus sandin_D': 30,
  'reese johnson_F': 4,
  'reilly smith_F': 46,
  'rickard rakell_F': 59,
  'ridly greig_F': 33,
  'rob bortuzzo_D': 2,
  'rob thomas_F': 94,
  'robby fabbri_F': 12,
  'robert bortuzzo_D': 2,
  'robert thomas_F': 94,
  'rodrigo abols_F': 28,
  'roman josi_D': 68,
  'ronnie attard_D': 23,
  'roope hintz_F': 64,
  'ross colton_F': 37,
  'ross johnston_F': 6,
  'rutger mcgroarty_F': 39,
  'ryan donato_F': 53,
  'ryan graves_D': 4,
  'ryan hartman_F': 44,
  'ryan johnson_D': 15,
  'ryan leonard_F': 19,
  'ryan lindgren_D': 20,
  'ryan lomberg_F': 10,
  'ryan mcdonagh_D': 36,
  'ryan mcleod_F': 36,
  'ryan nugenthopkins_F': 61,
  'ryan oreilly_F': 56,
  'ryan poehling_F': 33,
  'ryan pulock_D': 28,
  'ryan reaves_F': 7,
  'ryan shea_D': 7,
  'ryan strome_F': 45,
  'ryan suter_D': 5,
  'ryan winterton_F': 4,
  'ryker evans_D': 21,
  'sam bennett_F': 60,
  'sam bolduc_D': 4,
  'sam carrick_F': 19,
  'sam colangelo_F': 33,
  'sam dickinson_D': 3,
  'sam ersson_G': 64,
  'sam girard_D': 26,
  'sam helenius_F': 11,
  'sam lafferty_F': 14,
  'sam malinski_D': 21,
  'sam montembeault_G': 67,
  'sam reinhart_F': 90,
  'sam rinzel_D': 32,
  'sam steel_F': 25,
  'sammy blais_F': 4,
  'samuel bennett_F': 60,
  'samuel bolduc_D': 4,
  'samuel carrick_F': 19,
  'samuel colangelo_F': 33,
  'samuel dickinson_D': 3,
  'samuel ersson_G': 64,
  'samuel girard_D': 26,
  'samuel helenius_F': 11,
  'samuel lafferty_F': 14,
  'samuel malinski_D': 21,
  'samuel montembeault_G': 67,
  'samuel reinhart_F': 90,
  'samuel rinzel_D': 32,
  'samuel steel_F': 25,
  'scott laughton_F': 37,
  'scott mayfield_D': 11,
  'scott morrow_D': 8,
  'scott perunovich_D': 9,
  'scott sabourin_F': 41,
  'scott wedgewood_G': 29,
  'seamus casey_D': 32,
  'sean behrens_D': 27,
  'sean couturier_F': 47,
  'sean durzi_D': 38,
  'sean kuraly_F': 18,
  'sean monahan_F': 73,
  'sean walker_D': 23,
  'sebastian aho_D': 5,
  'sebastian aho_F': 91,
  'sergei bobrovsky_G': 78,
  'seth jarvis_F': 77,
  'seth jones_D': 53,
  'shakir mukhamadullin_D': 27,
  'shane pinto_F': 49,
  'shane wright_F': 48,
  'shayne gostisbehere_D': 58,
  'shea theodore_D': 68,
  'sidney crosby_F': 97,
  'simon benoit_D': 9,
  'simon edvinsson_D': 28,
  'simon holmstrom_F': 39,
  'simon nemec_D': 24,
  'sonny milano_F': 44,
  'spencer knight_G': 55,
  'spencer stastney_D': 11,
  'stefan noesen_F': 32,
  'steven lorentz_F': 16,
  'steven stamkos_F': 60,
  'stevie leskovar_D': 23,
  'stuart skinner_G': 78,
  'tage thompson_F': 73,
  'tanner jeannot_F': 16,
  'tanner pearson_F': 26,
  'taylor hall_F': 53,
  'taylor raddysh_F': 24,
  'teddy blueger_F': 27,
  'teuvo teravainen_F': 50,
  'thatcher demko_G': 65,
  'thomas bordeleau_F': 16,
  'thomas chabot_D': 48,
  'thomas harley_D': 48,
  'thomas wilson_F': 60,
  'tij iginla_F': 45,
  'tim liljegren_D': 23,
  'tim stutzle_F': 78,
  'tim washe_F': 39,
  'timo meier_F': 59,
  'timothy liljegren_D': 23,
  'timothy stutzle_F': 78,
  'timothy washe_F': 39,
  'tj brodie_D': 6,
  'tom bordeleau_F': 16,
  'tom chabot_D': 48,
  'tom harley_D': 48,
  'tom wilson_F': 60,
  'tomas hertl_F': 71,
  'tomas nosek_F': 9,
  'tomas tatar_F': 8,
  'tommy novak_F': 46,
  'tony deangelo_D': 33,
  'travis dermott_D': 3,
  'travis hamonic_D': 10,
  'travis konecny_F': 79,
  'travis sanheim_D': 39,
  'trent frederic_F': 33,
  'trevor lewis_F': 6,
  'trevor moore_F': 55,
  'trevor van riemsdyk_D': 20,
  'trevor zegras_F': 48,
  'tristan jarry_G': 70,
  'troy stecher_D': 9,
  'troy terry_F': 63,
  'ty dellandrea_F': 12,
  'ty emberson_D': 19,
  'tye kartye_F': 21,
  'tyler bertuzzi_F': 40,
  'tyler johnson_F': 14,
  'tyler kleven_D': 12,
  'tyler motte_F': 13,
  'tyler myers_D': 25,
  'tyler pitlick_F': 3,
  'tyler seguin_F': 62,
  'tyler toffoli_F': 52,
  'tyler tucker_D': 12,
  'tyson barrie_D': 9,
  'tyson foerster_F': 41,
  'tyson jost_F': 14,
  'tyson kozak_F': 17,
  'ukkopekka luukkonen_G': 62,
  'urho vaakanainen_D': 23,
  'uvis balinskis_D': 20,
  'valeri nichushkin_F': 70,
  'valtteri puustinen_F': 10,
  'vasily podkolzin_F': 25,
  'victor hedman_D': 76,
  'victor mancini_D': 7,
  'victor olofsson_F': 39,
  'viktor arvidsson_F': 36,
  'ville koivunen_F': 55,
  'vince dunn_D': 59,
  'vincent desharnais_D': 7,
  'vincent trocheck_F': 70,
  'vinni lettieri_F': 6,
  'vinnie hinostroza_F': 22,
  'vitek vanecek_G': 25,
  'vladimir tarasenko_F': 44,
  'vladislav gavrikov_D': 28,
  'vladislav kolyachonok_D': 25,
  'vladislav namestnikov_F': 41,
  'walker duehr_F': 5,
  'warren foegele_F': 41,
  'will borgen_D': 22,
  'will carrier_F': 18,
  'will cuylle_F': 31,
  'will eklund_F': 60,
  'will karlsson_F': 60,
  'will lagesson_D': 3,
  'will nylander_F': 91,
  'will smith_F': 52,
  'william borgen_D': 22,
  'william carrier_F': 18,
  'william cuylle_F': 31,
  'william eklund_F': 60,
  'william karlsson_F': 60,
  'william lagesson_D': 3,
  'william nylander_F': 91,
  'william smith_F': 52,
  'wyatt johnston_F': 66,
  'wyatt kaiser_D': 14,
  'xavier bourgault_F': 45,
  'yakov trenin_F': 16,
  'yanni gourde_F': 47,
  'yaroslav askarov_G': 60,
  'yegor chinakhov_F': 50,
  'yegor sharangovich_F': 48,
  'zac jones_D': 7,
  'zach astonreese_F': 17,
  'zach benson_F': 33,
  'zach bogosian_D': 17,
  'zach hyman_F': 55,
  'zach lheureux_F': 7,
  'zach werenski_D': 81,
  'zach whitecloud_D': 16,
  'zachary astonreese_F': 17,
  'zachary benson_F': 33,
  'zachary bogosian_D': 17,
  'zachary hyman_F': 55,
  'zachary lheureux_F': 7,
  'zachary werenski_D': 81,
  'zachary whitecloud_D': 16,
  'zack bolduc_F': 35,
  'zack macewen_F': 3,
  'zack ostapchuk_F': 5,
  'zakhar bardakov_F': 51,
  'zayne parekh_D': 23,
  'zeev buium_D': 22,
  'zemgus girgensons_F': 12
};
